# Generated by Django 3.1.2 on 2022-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=1234, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
